{% set version = "6.5.4" %}

package:
  name: ogs
  version: {{ version }}

source:
  url: https://github.com/ufz/ogs/archive/refs/tags/{{ version }}.tar.gz
  sha256: 86d2446a3d9cb8d5323afcfb259a468ea2dd16a1d5922c24cfcbd298e2ec209e

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - libgomp                                # [linux]
    - llvm-openmp                            # [osx]
  host:
    - eigen
    - exprtk
    - hdf5
    - libboost-python-devel
    - libxml2
    - metis
    - nlohmann_json
    - pybind11
    - python
    - range-v3
    - tclap
    - vtk >=9.3.0
    - zlib
  run:
    - tetgen
    - python

test:
  commands:
    - ogs --version

about:
  home: http://www.opengeosys.org/
  summary: OpenGeoSys (OGS) THMC simulator.
  description: |
    OpenGeoSys (OGS) is a scientific open source project for the development
    of numerical methods for the simulation of thermo-hydro-mechanical-
    chemical (THMC) processes in porous and fractured media. 
  license: BSD-3-Clause
  license_family: BSD
  license_file:
    - LICENSE.txt
    - scripts/cmake/json-cmake/LICENSE
    - build/third_party_licenses.txt
  doc_url: https://www.opengeosys.org/docs
  dev_url: https://gitlab.opengeosys.org/ogs/ogs

extra:
  recipe-maintainers:
    - bilke
